# Gitleaks configuration for VibeFlow
title = "VibeFlow Secret Detection"

[extend]
useDefault = true

[[rules]]
id = "anthropic-api-key"
description = "Anthropic API Key"
regex = '''sk-ant-api03-[A-Za-z0-9_-]{95}'''
secretGroup = 1

[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[A-Za-z0-9]{48}'''
secretGroup = 1

[[rules]]
id = "claude-code-token"
description = "Claude Code Token"
regex = '''cc_[A-Za-z0-9_-]{32,}'''
secretGroup = 1

[[rules]]
id = "mastra-token"
description = "Mastra Token"
regex = '''mastra_[A-Za-z0-9_-]{32,}'''
secretGroup = 1

# Allowlist configuration
[allowlist]
description = "Allowlist for test files and documentation"
files = [
    '''.gitleaks.toml''',
    '''README.md''',
    '''docs/.*''',
    '''CLAUDE.md''',
    '''.claude/.*'''
]

paths = [
    '''node_modules/.*''',
    '''dist/.*''',
    '''\.git/.*''',
    '''workspace/.*''',
    '''.*\.test\..*''',
    '''.*\.spec\..*'''
]

regexes = [
    '''(?i)example''',
    '''(?i)placeholder''',
    '''(?i)dummy''',
    '''(?i)test''',
    '''(?i)mock'''
]

commits = []